block: maple-iosched,zen-iosched: Convert fifo_time from ulong to u64
Currently rq->fifo_time is unsigned long but CFQ stores nanosecond
timestamp in it which would overflow on 32-bit archs. Convert it to u64
to avoid the overflow. Since the rq->fifo_time is unioned with struct
call_single_data(), this does not change the size of struct request in
any way.

Fixes compare-distinct-pointer-types warning:

../block/maple-iosched.c:69:7: error: comparison of distinct pointer types
('unsigned long *' and 'typeof (rq->fifo_time) *' (aka 'unsigned long long *'))
[-Werror,-Wcompare-distinct-pointer-types]
                if (time_before(next->fifo_time, rq->fifo_time)) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/jiffies.h:105:26: note: expanded from macro 'time_before'
                                ^~~~~~~~~~~~~~~
../include/linux/jiffies.h:102:3: note: expanded from macro 'time_after'
        (typecheck(unsigned long, a) && \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/typecheck.h:11:18: note: expanded from macro 'typecheck'
        (void)(&__dummy == &__dummy2); \
               ~~~~~~~~ ^  ~~~~~~~~~
../block/maple-iosched.c:69:7: error: comparison of distinct pointer types
('unsigned long *' and 'typeof (next->fifo_time) *' (aka 'unsigned long long *'))
[-Werror,-Wcompare-distinct-pointer-types]
                if (time_before(next->fifo_time, rq->fifo_time)) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/jiffies.h:105:26: note: expanded from macro 'time_before'
                                ^~~~~~~~~~~~~~~
../include/linux/jiffies.h:103:3: note: expanded from macro 'time_after'
         typecheck(unsigned long, b) && \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/typecheck.h:11:18: note: expanded from macro 'typecheck'
        (void)(&__dummy == &__dummy2); \
               ~~~~~~~~ ^  ~~~~~~~~~
../block/maple-iosched.c:115:6: error: comparison of distinct pointer types
('unsigned long *' and 'typeof (rq->fifo_time) *' (aka 'unsigned long long *'))
[-Werror,-Wcompare-distinct-pointer-types]
        if (time_after_eq(jiffies, rq->fifo_time))
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/jiffies.h:109:3: note: expanded from macro 'time_after_eq'
         typecheck(unsigned long, b) && \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/typecheck.h:11:18: note: expanded from macro 'typecheck'
        (void)(&__dummy == &__dummy2); \
               ~~~~~~~~ ^  ~~~~~~~~~
../block/maple-iosched.c:138:7: error: comparison of distinct pointer types
('unsigned long *' and 'typeof (rq_sync_read->fifo_time) *' (aka 'unsigned long long *'))
[-Werror,-Wcompare-distinct-pointer-types]
                if (time_after(rq_sync_read->fifo_time, rq_async_read->fifo_time))
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/jiffies.h:102:3: note: expanded from macro 'time_after'
        (typecheck(unsigned long, a) && \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/typecheck.h:11:18: note: expanded from macro 'typecheck'
        (void)(&__dummy == &__dummy2); \
               ~~~~~~~~ ^  ~~~~~~~~~
../block/maple-iosched.c:138:7: error: comparison of distinct pointer types
('unsigned long *' and 'typeof (rq_async_read->fifo_time) *' (aka 'unsigned long long *'))
[-Werror,-Wcompare-distinct-pointer-types]
                if (time_after(rq_sync_read->fifo_time, rq_async_read->fifo_time))
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/jiffies.h:103:3: note: expanded from macro 'time_after'
         typecheck(unsigned long, b) && \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/typecheck.h:11:18: note: expanded from macro 'typecheck'
        (void)(&__dummy == &__dummy2); \
               ~~~~~~~~ ^  ~~~~~~~~~
../block/maple-iosched.c:147:7: error: comparison of distinct pointer types
('unsigned long *' and 'typeof (rq_sync_write->fifo_time) *' (aka 'unsigned long long *'))
[-Werror,-Wcompare-distinct-pointer-types]
                if (time_after(rq_sync_write->fifo_time, rq_async_write->fifo_time))
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/jiffies.h:102:3: note: expanded from macro 'time_after'
        (typecheck(unsigned long, a) && \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/typecheck.h:11:18: note: expanded from macro 'typecheck'
        (void)(&__dummy == &__dummy2); \
               ~~~~~~~~ ^  ~~~~~~~~~
../block/maple-iosched.c:147:7: error: comparison of distinct pointer types
('unsigned long *' and 'typeof (rq_async_write->fifo_time) *' (aka 'unsigned long long *'))
[-Werror,-Wcompare-distinct-pointer-types]
                if (time_after(rq_sync_write->fifo_time, rq_async_write->fifo_time))
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/jiffies.h:103:3: note: expanded from macro 'time_after'
         typecheck(unsigned long, b) && \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/typecheck.h:11:18: note: expanded from macro 'typecheck'
        (void)(&__dummy == &__dummy2); \
               ~~~~~~~~ ^  ~~~~~~~~~

Change-Id: I91868a6002d58c408aaf15786e6bdb5a6b9cb02e
Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>